export * from './info';
export * from './sections';
export * from './mir-dit';
export { default as Company } from './Company.svelte';
export { default as Links } from './Links.svelte';
export { default as MouseIcon } from './MouseIcon.svelte';
export { default as Personal } from './Personal.svelte';
export { default as ResumeBlock } from './ResumeBlock.svelte';
export { default as Footer } from './Footer.svelte';
export { default as Skills } from './Skills.svelte';